### ISSUE TITLE
Can't see snapshot 

### ISSUE THREAD

**Issue by satyajitdas75** [fedspendingtransparency/usaspending-api#1413]
I don't see the snapshot. Is it still available?

**Comment by jqnatividad** [comment]
Hi @satyajitdas75,

Just go to https://aws.amazon.com/blogs/aws/new-usaspending-gov-on-an-amazon-rds-snapshot/

**Comment by datocrats-org** [comment]
We need the snapshot S3 bucket info or its Header, URL, Bytes, md5 hash metadata in order to pull it into google cloud platform of the form, e.g., https://cloud.google.com/storage-transfer/docs/create-url-list#md5
`TsvHttpData-1.0
https://example.com/buckets/obj1      1357      wHENa08V36iPYAsOa2JAdw==
https://example.com/buckets/obj2      2468      R9acAaveoPd2y8nniLUYbw==`

**Comment by datocrats-org** [comment]
I tried to get this working with google cloud platform, got pretty far into the weeds before getting an error in the script on https://files.usaspending.gov/database_download/usaspending-db-setup.pdf 

It would help to simplify it or to help troubleshoot!

[Shell history.txt](https://github.com/fedspendingtransparency/usaspending-api/files/2814261/Shell.history.txt)

**Comment by lisaam** [comment]
@datocrats-org  We apologize for the delay in answering your question during the government shutdown.  The most recent version of the full database snapshot is available for download here:

https://files.usaspending.gov/database_download/usaspending-db_20190129.zip

For assistance setting up an S3 bucket on your Google Cloud-hosted standup of the snapshot, please contact your Google Cloud representative.

**Comment by rdg7739** [comment]
Is there any plan to make this snapshot available in AWS or will serving the snapshot from usaspending.gov site only?

**Comment by lisaam** [comment]
From USAspending.gov only
