### ISSUE TITLE
/download/awards/ requiring undocumented properties

### ISSUE THREAD

**Issue by seraphx2** [fedspendingtransparency/usaspending-api#1577]
When trying to use [/download/awards/](https://github.com/fedspendingtransparency/usaspending-api/blob/stg/usaspending_api/api_docs/api_documentation/download/advanced_search_award_download.md), I get a response with a filename, but when I check /download/status/ I get this response:
```
{
    "detail": "Missing one or more required query parameters: award_levels"
}
```

The documentation does not address having to provide an award_level. I am trying to do a test request with a random DUNS:

```
{
    "filters": {
    	"recipient_search_text": ["113253443"]
    },
    "columns": [
        "award_type",
        "awarding_agency_code"
    ]
}
```

And what's worse, I get the same error message with the example JSON that is provided in the documentation.

**Comment by seraphx2** [comment]
bump?

**Comment by lisaam** [comment]
The API /download/status/ endpoint is a GET request.  Here is an example call:

https://api.usaspending.gov/api/v2/download/status/?file_name=file_name.zip&type=awards

To get the status for a specific file generation, simply replace "file_name.zip" above with the name of the ZIP file being generated.  Currently, "type" will always be "awards".  Different "type" vales are planned future functionality.

Thank you for letting us know that this endpoint's documentation does not have a GET example or list all the required query parameters.  We have informed our technical team so that they can update the documentation.

**Comment by seraphx2** [comment]
Ahh, ok. Thanks!

**Comment by seraphx2** [comment]
Umm, actually, this didn't work either. The download status endpoint is still telling me:
![image](https://user-images.githubusercontent.com/11561820/47542980-fc61a680-d8ad-11e8-94b6-bb827cd57026.png)

**Comment by lisaam** [comment]
This is one of the rare cases where the USAspending API uses a GET request.

The /download/status/ endpoint only accepts GET requests.  To receive a valid response, please change the drop down call option from POST to GET.

**Comment by seraphx2** [comment]
ahh. sorry. I knew that and thought I had done that last time and didn't even bother to check. thanks

Robert Burke | Gamer / Developer
Sent from Outlook<https://aka.ms/qtex0l> on my iPhone

________________________________
