### ISSUE TITLE
/search/spending_by_award/ erroring on filter field

### ISSUE THREAD

**Issue by seraphx2** [fedspendingtransparency/usaspending-api#1578]
When using the [/search/spending_by_award/](https://github.com/fedspendingtransparency/usaspending-api/blob/stg/usaspending_api/api_docs/api_documentation/advanced_award_search/spending_by_award.md) endpoint, I am getting the following response with the example JSON request that is in the documentation:
```
{
    "detail": "Field 'filters|legal_entities' value '779928' is above max '5000'"
}
```

I was specifically wanting to query against legal_entities and had to remove award_ids to see the above error because if award_ids is in the filter set, it also causes an error:
```
{
    "detail": "Invalid value in 'filters|award_ids'. '1018950' is not a valid type (text)"
}
```

**Comment by seraphx2** [comment]
bump?

**Comment by lisaam** [comment]
It looks like the example call in the /search/spending_by_award/ documentation needs to be updated to reflect the newest version of the API - the filters listed are from a previous version.  In the meantime, the list of valid POST request filter fields with their allowable inputs is available here:

https://github.com/fedspendingtransparency/usaspending-api/blob/stg/usaspending_api/api_docs/api_documentation/search_filters.md

For "legal_entities" data filtering, use the Recipient filters.  For "award_ids" filtering, please make sure that the filter input is encased in quotes (" " or ' ') so that it parses as text.

Thank you for letting us know that the documentation example filters are from a previous API version.  We have informed our technical team so that they can update the documentation.

**Comment by datocrats-org** [comment]
The API documentation also needs the following updates to reflect changes:
- [/api_docs/api_documentation/search_filters.md](https://github.com/fedspendingtransparency/usaspending-api/blob/stg/usaspending_api/api_docs/api_documentation/search_filters.md): Each example should return results, both by itself and in continuation of another example.  Otherwise it is just a description, not an example.  
- Examples should not use any pizza analogies, it is not helpful and is a mockery "Office of Pizza" 
- **recipient_locations** and **place_of_performance_locations** need to be objects 
- **award_amounts** : **lower_bound** of 0 returns `{"detail": "Field 'filters|award_amounts' value '0.0' is below min '2.2250738585072014e-308'"}`

**Comment by lisaam** [comment]
We apologize for the delay in addressing your inquiry during the government shutdown.

Thank you for your suggested updates to the USAspending API documentation.  We have passed along your suggestion to our technical team for consideration in their ongoing documentation update efforts.

**Comment by tony-sappe** [comment]
Thanks for the detailed notes on our documentation. We will group all API issues under #1660
