### ISSUE TITLE
Names of Fields?

### ISSUE THREAD

**Issue by lhux** [fedspendingtransparency/usaspending-api#2007]
What are the names of the fields in the API if you want to pull "number_of_offers_received" and "other_than_full_and_open_competition_code" from the v2/search/spending_by_award endpoint? I can't seem to find it in the documentation.

**Comment by lisaam** [comment]
Please see https://github.com/fedspendingtransparency/usaspending-api/issues/2004#issuecomment-526645478 about specifying columns.


The fields are:
number_of_offers_received
other_than_full_and_open_competition_code

The data dictionary is available at https://www.usaspending.gov/#/download_center/data_dictionary

**Comment by lhux** [comment]
When I use those, I just get blank columns?

**Comment by lisaam** [comment]
Ok, let me troubleshoot. What's your query string?

**Comment by lhux** [comment]
params = {"filters":{"time_period":[{"start_date":"2018-10-01","end_date":"2019-09-30"}],"award_type_codes":["A","B","C","D"],"recipient_search_text":["152670030"]},"fields":["Award ID","Recipient Name","Description","Start Date","End Date","other_than_full_and_open_competition_code","Awarding Agency Code","number_of_offers_received","Funding Sub Agency","Funding Agency","Award Amount","Awarding Agency","Awarding Sub Agency","Contract Award Type"],"page":1,"limit":60,"sort":"Award Amount","order":"desc","subawards":"false"}

**Comment by lhux** [comment]
@lisaam were you able to figure it out?

**Comment by lisaam** [comment]
Hi,

Sorry for the delay. I worked with Brian on this and determined there is a bug that generates 'null' for "number_of_offers_received" and "other_than_full_and_open_competition_code" in an API call like this.
 
Until we get the bug fixed the only way you'll be able to download this information for multiple awards is with Advanced Search or Customer Award Data download on USAspending.gov. I know this gives you more columns than you want but it will return accurate information.

Thank you very much for identifying this issue and reaching out to us. The bug is documented here: https://federal-spending-transparency.atlassian.net/browse/DEV-3452

**Comment by mviterna** [comment]
This is still an issue. Any update on it? The number of offerors field is null here, but should be 5. Opened a new ticket : #4379 


{
  "filters": {
    "time_period": [
      {
        "start_date": "2007-10-01",
        "end_date": "2025-09-30"
      }
    ],
    "award_type_codes": [
      "A",
      "B",
      "C",
      "D"
    ],
    "recipient_search_text": [
      "WLWRCWJAH9Q8"
    ]
  },
  "fields": [
    "Recipient UEI",
    "Award ID",
    "Recipient Name",
    "Award Amount",
    "Total Outlays",
    "Description",
    "Contract Award Type",
    "def_codes",
    "COVID-19 Obligations",
    "COVID-19 Outlays",
    "Infrastructure Obligations",
    "Infrastructure Outlays",
    "Awarding Agency",
    "Awarding Sub Agency",
    "Start Date",
    "End Date",
    "recipient_id",
    "prime_award_recipient_id",
    "number_of_offers_received"
  ],
  "page": 1,
  "limit": 100,
  "sort": "Award Amount",
  "order": "desc",
  "subawards": false,
  "auditTrail": "Results Table - Spending by award search"
}
